version: '3.8'

services:
  web:
    build: .
    ports:
      - "3005:3000"
    environment:
      - PORT=3000
      # Example of passing secrets via environment variables (set these locally or in your orchestration)
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - HF_MODEL=${HF_MODEL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_TO=${SMTP_TO}
      - RECAPTCHA_SECRET=${RECAPTCHA_SECRET}
    volumes:
      - ./:/usr/src/app:ro
    restart: unless-stopped
