name: Auto Blog Draft
on:
  schedule:
    - cron: "0 9 * * 0"   # Sundays 2am PT (9am UTC)
  workflow_dispatch: {}

jobs:
  draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate blog post
        id: generate
        run: |
          # Run the reliable blog generator
          npm run blog:generate:reliable
          
          # Find the generated file in staging
          FILE=$(ls -t content/blog/staging/*.md 2>/dev/null | head -n1)
          
          if [ -z "$FILE" ]; then
            echo "No blog post generated"
            exit 1
          fi
          
          # Move from staging to published
          BASENAME=$(basename "$FILE")
          mv "$FILE" "content/blog/$BASENAME"
          
          echo "FILE=content/blog/$BASENAME" >> $GITHUB_OUTPUT
          echo "Generated: $BASENAME"

      - name: Save output variable
        id: savefile
        run: |
          FILE="${{ steps.generate.outputs.FILE }}"
          echo "FILE=$FILE" >> $GITHUB_OUTPUT

      - name: Commit branch & open draft PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(blog): auto-draft ${{ steps.savefile.outputs.FILE }}"
          title: "Weekly Blog Draft"
          body: "AI-drafted post from repo knowledge. Please review, edit, and merge to publish."
          branch: "blog-draft-${{ github.run_id }}"
          base: "main"
          labels: "blog-draft"
          draft: true
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"