name: Build site and upload artifact

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci
      - name: Build Eleventy
        run: npm run build
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
